# Generated by Django 3.2.7 on 2021-11-23 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211122_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 6, 42, 42, 346835, tzinfo=utc)),
        ),
    ]
