# Generated by Django 3.2.7 on 2021-11-24 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_room_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 1, 9, 41, 970046, tzinfo=utc)),
        ),
    ]
