# Generated by Django 3.2.9 on 2021-11-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_room_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
