# Generated by Django 3.2.9 on 2021-12-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
