# Generated by Django 3.2.9 on 2023-04-16 14:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=main.models.upload_to),
        ),
    ]
