# Generated by Django 3.2.9 on 2021-12-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
